// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int numOfTimes = Integer.parseInt(args[0]);
	   int countGreater = 0;
	   int countLessOrEqual = 0;
	   for (int i = 0; i < numOfTimes; i++) {
          if (Math.random() > 0.5) {
			countGreater++;
		  } else {
			countLessOrEqual++;
		  }
	   }
	   if (countGreater == 0 || countLessOrEqual == 0) {
		System.out.println("< 0.5: " + countGreater + " times");
		System.out.println(">= 0.5: " + countLessOrEqual + " times");
	   } else {
        System.out.println("< 0.5: " + countGreater + " times");
		System.out.println(">= 0.5: " + countLessOrEqual + " times");
		double ratio = (double) countGreater/countLessOrEqual;
		System.out.println("Ratio: " + ratio);
	   }
	}
}
